-- ========================================================================
-- 【UI数据[$$smallcard_inventory.inventory_config.通用背包配置]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$smallcard_inventory.inventory_config.通用背包配置
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$smallcard_inventory.inventory_config.通用背包配置
    #CONFIG = {
        'X' = 570.60350222906,
        'Y' = 50.463726309122,
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.ActorEffect
    'ActorEffect' = {
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.ActorEffect_1
    'ActorEffect_1' = {
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.ActorEffect_2
    'ActorEffect_2' = {
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.ActorEffect_3
    'ActorEffect_3' = {
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.ActorEffect_4
    'ActorEffect_4' = {
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.Particle
    'Particle' = {
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.Particle_1
    'Particle_1' = {
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.Particle_2
    'Particle_2' = {
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.Particle_3
    'Particle_3' = {
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.Particle_4
    'Particle_4' = {
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.Quality_Color
    'Quality_Color' = {
        'H' = 213.33333333333,
        'W' = 464.11111111111,
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.Quality_Color_1
    'Quality_Color_1' = {
        'W' = 465.5,
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.Quality_Color_2
    'Quality_Color_2' = {
        'W' = 465.5,
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.Quality_Color_3
    'Quality_Color_3' = {
        'W' = 465.5,
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.Quality_Color_4
    'Quality_Color_4' = {
        'W' = 465.5,
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.Quality_Color_5
    'Quality_Color_5' = {
        'W' = 465.5,
    },
    -- <EntryNode>: $$smallcard_inventory.inventory_config.通用背包配置.root
    'root' = {
        'H' = 1589.1203703704,
        'W' = 701.61111111111,
    },
}
-- ************************************************************************