-- ========================================================================
-- 【实例模块[unit.防御塔1_4]配置文件】
-- 说明：
--   1、#NIL代表强制赋值为nil，无视继承值。
--   2、#CONFIG代表当前配置文件对应实例模块自身的配置。
-- ========================================================================

-- ************************************************************************
[#CONFIG]
'Version' = 14
'DisplayName' = '[EntryModule][$$p_3b4f.unit.防御塔1_4].DisplayName'
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.ActorEffect]
['ActorEffect']
'Version' = 1
'NodeType' = '$$.actor.ActorEffect'
'Inherit' = '$$.template@actor.ActorEffect.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Offset' = {
            'Z' = 450,
        },
        'Effect' = 'Particle',
        'Scale' = 0.5,
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.ActorEffect_1]
['ActorEffect_1']
'Version' = 1
'NodeType' = '$$.actor.ActorEffect'
'Inherit' = '$$.template@actor.ActorEffectOneShot.root'
'Data' = {
    'Editor' = {
        'EditorSuffix' = '1',
    },
    'Game' = {
        'Effect' = 'Particle_1',
        'Scale' = 3.5,
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.ActorSite]
['ActorSite']
'Version' = 1
'NodeType' = '$$.actor.ActorSite'
'Inherit' = '$$.template@actor.ActorCameraShake.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Amplitude' = 10,
        'Time' = 1,
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.CreateUnit]
['CreateUnit']
'Version' = 1
'NodeType' = '$$.effect.EffectCreateUnit'
'Inherit' = '$$.template@effect.EffectCreateUnit.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'SpawnUnitTypePerLevel' = {
            1 = 'unit.站位.root',
            'IsOverwrite' = true,
            #IS_OVERWRITE = true,
        },
        'SpawnOwner' = {
            'Value' = 'Neutral',
        },
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.Damage]
['Damage']
'Version' = 1
'NodeType' = '$$.effect.EffectDamage'
'Inherit' = '$$.template@effect.EffectDamage.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Amount' = {
            'IsFunc' = false,
            'Value' = 1500,
            'LuaCode' = '(function ()\r\n        local func = function (EffectParam)\r\n            return 1500\r\n        end\r\n        return func\r\n    end)()',
        },
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.Model]
['Model']
'Version' = 1
'NodeType' = '$$.model.Model'
'Inherit' = '$$.template@model.Model.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Asset' = 'deco/dungeon/sk_garden_stonetower_a05/model.prefab',
        'AnimMapping' = {
            #IS_OVERWRITE = true,
        },
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.Particle]
['Particle']
'Version' = 1
'NodeType' = '$$.particle.Particle'
'Inherit' = '$$.template@particle.Particle.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Asset' = 'effect/effect_new/effect_yinchangxuli/eff_xuli_06/particle.effect',
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.Particle_1]
['Particle_1']
'Version' = 1
'NodeType' = '$$.particle.Particle'
'Inherit' = '$$.template@particle.Particle.root'
'Data' = {
    'Editor' = {
        'EditorSuffix' = '1',
    },
    'Game' = {
        'Asset' = 'effect/effect_new/effect_hit/ps_firering_hit_eff/particle.effect',
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.RandomDelay]
['RandomDelay']
'Version' = 1
'NodeType' = '$$.effect.EffectRandomDelay'
'Inherit' = '$$.template@effect.EffectRandomDelay.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'BaseAmount' = {
            'Value' = 3,
            'LuaCode' = '(function ()\r\n        local func = function (EffectParam)\r\n            return 3\r\n        end\r\n        return func\r\n    end)()',
        },
        'Effect' = 'Set',
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.Search]
['Search']
'Version' = 1
'NodeType' = '$$.effect.EffectSearch'
'Inherit' = '$$.template@effect.EffectSearch.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'ActorArray' = {
            1 = 'ActorEffect_1',
            2 = 'ActorSite',
        },
        'Radius' = {
            'Value' = 1600,
            'LuaCode' = '(function ()\r\n        local func = function (EffectParam)\r\n            return 1600\r\n        end\r\n        return func\r\n    end)()',
        },
        'SearchEffect' = 'Damage',
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.Set]
['Set']
'Version' = 1
'NodeType' = '$$.effect.EffectSet'
'Inherit' = '$$.template@effect.EffectSet.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'EffectArray' = {
            1 = 'CreateUnit',
            2 = 'Search',
            3 = 'UnitKill',
        },
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.Spell_1]
['Spell_1']
'Version' = 1
'NodeType' = '$$.spell.Spell'
'Inherit' = '$$.template@spell.SpellRootPassive.root'
'Data' = {
    'Editor' = {
        'EditorSuffix' = '1',
    },
    'Game' = {
        'SpellEventEffects' = {
            'on_disable' = #PLACEHOLDER,
            'on_enable' = 'RandomDelay',
        },
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.UnitKill]
['UnitKill']
'Version' = 1
'NodeType' = '$$.effect.EffectUnitKill'
'Inherit' = '$$.template@effect.EffectUnitKill.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_4.root]
['root']
'Version' = 1
'NodeType' = '$$.unit.Unit'
'Inherit' = '$$spark_core.template@unit.UnitStructure.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Name' = '[EntryNode][$$p_3b4f.unit.防御塔1_4.root].Data.Game.Name',
        'Attribute' = {
            '攻击' = #PLACEHOLDER,
            '攻击速度' = #PLACEHOLDER,
            '生命' = #PLACEHOLDER,
            '生命上限' = #PLACEHOLDER,
            '搜敌范围' = 1000,
        },
        'ActorArray' = {
            1 = 'ActorEffect',
        },
        'UnitData' = {
            'HeroSkill' = {
                1 = 'Spell_1',
            },
            'Block' = {
                'Footpoint' = [[■■■■■
■■■■■
■■■■■
■■■■■
■■■■■]],
            },
            'DeadSink' = 0,
        },
        'ModelData' = 'Model',
    },
}
'UIConfig' = {
}
-- ************************************************************************