-- ========================================================================
-- 【UI数据[$$p_3b4f.unit.防御塔1_4]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_3b4f.unit.防御塔1_4
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_3b4f.unit.防御塔1_4
    #CONFIG = {
        'Scale' = 1.2,
        'Type' = 'EntryModule',
        'X' = -1684.5,
        'Y' = 310.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.ActorEffect
    'ActorEffect' = {
        'AttachedTo' = 'root',
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 242.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.ActorEffect_1
    'ActorEffect_1' = {
        'AttachedTo' = 'Search',
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 312.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.ActorSite
    'ActorSite' = {
        'AttachedTo' = 'Search',
        'H' = 189.0,
        'Type' = 'EntryNode',
        'W' = 208,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.CreateUnit
    'CreateUnit' = {
        'H' = 316.66666666667,
        'Type' = 'EntryNode',
        'W' = 356.33333333333,
        'X' = 2054.6666666667,
        'Y' = -24.166666666667,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.Damage
    'Damage' = {
        'H' = 266.66666666667,
        'Type' = 'EntryNode',
        'W' = 211.33333333333,
        'X' = 2541.3333333333,
        'Y' = 455.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.Model
    'Model' = {
        'H' = 142.5,
        'Type' = 'EntryNode',
        'W' = 386.33333333333,
        'X' = 666.0,
        'Y' = 473.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.Particle
    'Particle' = {
        'H' = 118.33333333333,
        'Type' = 'EntryNode',
        'W' = 386.33333333333,
        'X' = 624.0,
        'Y' = 678.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.Particle_1
    'Particle_1' = {
        'H' = 118.33333333333,
        'Type' = 'EntryNode',
        'W' = 386.33333333333,
        'X' = 2529.8333333333,
        'Y' = 840.5,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.RandomDelay
    'RandomDelay' = {
        'H' = 216.66666666667,
        'Type' = 'EntryNode',
        'W' = 419.83333333333,
        'X' = 1167.9671193503,
        'Y' = 118.46650379978,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.Search
    'Search' = {
        'H' = 800.0,
        'Type' = 'EntryNode',
        'W' = 419.66666666667,
        'X' = 2067.1666666667,
        'Y' = 314.16666666667,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.Set
    'Set' = {
        'H' = 286.66666666667,
        'Type' = 'EntryNode',
        'W' = 299.66666666667,
        'X' = 1700.1197415725,
        'Y' = 376.26050379978,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.Spell_1
    'Spell_1' = {
        'H' = 374.16666666667,
        'Type' = 'EntryNode',
        'W' = 426.33333333333,
        'X' = 625.70045268364,
        'Y' = -14.733496200219,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.UnitKill
    'UnitKill' = {
        'H' = 176.66666666667,
        'Type' = 'EntryNode',
        'W' = 208,
        'X' = 2047.2030749059,
        'Y' = 1258.3438371331,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_4.root
    'root' = {
        'H' = 468.33333333333,
        'Type' = 'EntryNode',
        'W' = 263.0,
        'X' = 289.0,
        'Y' = 305.0,
    },
}
-- ************************************************************************