-- ========================================================================
-- 【UI数据[$$p_3b4f.item.塔1_3]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_3b4f.item.塔1_3
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_3b4f.item.塔1_3
    #CONFIG = {
        'Scale' = 1.0,
        'Type' = 'EntryModule',
        'X' = -263.31447692402,
        'Y' = 339.0,
    },
    -- <EntryNode>: $$p_3b4f.item.塔1_3.default_units_ts_Unit
    'default_units_ts_Unit' = {
        'H' = 318.0,
        'Type' = 'EntryNode',
        'W' = 315.0,
        'X' = 982.81447692402,
        'Y' = -128.0,
    },
    -- <EntryNode>: $$p_3b4f.item.塔1_3.root
    'root' = {
        'H' = 364.0,
        'Type' = 'EntryNode',
        'W' = 647.0,
        'X' = 300,
        'Y' = 0,
    },
    -- <Lnk>: $$p_3b4f.spell.新建防御塔_3.root
    'spell.新建防御塔_3.root' = {
        'H' = 79.0,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1084.314476924,
        'Y' = 305.0,
    },
}
-- ************************************************************************