-- ========================================================================
-- 【UI数据[$$.template@gui_ctrl.GuiCtrl]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$.template@gui_ctrl.GuiCtrl
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$.template@gui_ctrl.GuiCtrl
    #CONFIG = {
        'Scale' = 1.289945088,
        'X' = -454.80255513542,
        'Y' = 982.56699233224,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_attachable_panel
    'p_3b4f_attachable_panel' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_label
    'p_3b4f_label' = {
        'H' = 82.947530864198,
        'Type' = 'EntryNode',
        'W' = 208,
        'X' = 1500,
        'Y' = 900,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_label_1
    'p_3b4f_label_1' = {
        'H' = 85.19804526749,
        'Type' = 'EntryNode',
        'W' = 208,
        'X' = 1500,
        'Y' = 600,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_label_10
    'p_3b4f_label_10' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_label_11
    'p_3b4f_label_11' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_label_13
    'p_3b4f_label_13' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_label_14
    'p_3b4f_label_14' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_label_2
    'p_3b4f_label_2' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_label_8
    'p_3b4f_label_8' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_label_9
    'p_3b4f_label_9' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_normal_btn
    'p_3b4f_normal_btn' = {
        'H' = 83.724494170096,
        'Type' = 'EntryNode',
        'W' = 269.19644132945,
        'X' = 1500,
        'Y' = 0,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_normal_btn_1
    'p_3b4f_normal_btn_1' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_normal_btn_2
    'p_3b4f_normal_btn_2' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_normal_btn_3
    'p_3b4f_normal_btn_3' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_normal_btn_5
    'p_3b4f_normal_btn_5' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_normal_rect
    'p_3b4f_normal_rect' = {
        'H' = 225.05144032922,
        'Type' = 'EntryNode',
        'W' = 208,
        'X' = 600,
        'Y' = 600,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_normal_rect_2
    'p_3b4f_normal_rect_2' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_panel
    'p_3b4f_panel' = {
        'H' = 83.724494170096,
        'Type' = 'EntryNode',
        'W' = 208,
        'X' = 900,
        'Y' = 300,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_panel_1
    'p_3b4f_panel_1' = {
        'H' = 83.724494170096,
        'Type' = 'EntryNode',
        'W' = 208,
        'X' = 300,
        'Y' = 300,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_panel_2
    'p_3b4f_panel_2' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_panel_4
    'p_3b4f_panel_4' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.p_3b4f_panel_5
    'p_3b4f_panel_5' = {
        'Type' = 'EntryNode',
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.root
    'root' = {
        'H' = 83.724494170096,
        'W' = 208,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_inventory_背包入口
    'smallcard_inventory_背包入口' = {
        'H' = 82.947530864198,
        'W' = 286.25143088261,
        'X' = 0,
        'Y' = 900,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_panel
    'smallcard_store_panel' = {
        'H' = 83.724494170096,
        'W' = 208,
        'X' = 0,
        'Y' = 300,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_panel_1
    'smallcard_store_panel_1' = {
        'H' = 82.947530864198,
        'W' = 208,
        'X' = 600,
        'Y' = 900,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_panel_3
    'smallcard_store_panel_3' = {
        'H' = 85.648148148148,
        'W' = 208,
        'X' = 300,
        'Y' = 1200,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_panel_4
    'smallcard_store_panel_4' = {
        'H' = 82.947530864198,
        'W' = 208,
        'X' = 900,
        'Y' = 900,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_商店_关闭按钮
    'smallcard_store_商店_关闭按钮' = {
        'H' = 85.19804526749,
        'W' = 356.02184269103,
        'X' = 1200,
        'Y' = 600,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_商店_合成面板
    'smallcard_store_商店_合成面板' = {
        'H' = 83.724494170096,
        'W' = 356.02184269103,
        'X' = 1500,
        'Y' = 300,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_商店_合成页签
    'smallcard_store_商店_合成页签' = {
        'H' = 83.724494170096,
        'W' = 356.02184269103,
        'X' = 600,
        'Y' = 300,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_商店_商品面板
    'smallcard_store_商店_商品面板' = {
        'H' = 83.724494170096,
        'W' = 356.02184269103,
        'X' = 900,
        'Y' = 0,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_商店_商店面板
    'smallcard_store_商店_商店面板' = {
        'H' = 538.78262452053,
        'W' = 355.24661589316,
        'X' = 1032.6528,
        'Y' = -820.83072,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_商店_玩家属性
    'smallcard_store_商店_玩家属性' = {
        'H' = 82.947530864198,
        'W' = 356.02184269103,
        'X' = 1200,
        'Y' = 900,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_商店_目录
    'smallcard_store_商店_目录' = {
        'H' = 82.947530864198,
        'W' = 300.2055132443,
        'X' = 300,
        'Y' = 900,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_商店_筛选页签_1
    'smallcard_store_商店_筛选页签_1' = {
        'H' = 85.19804526749,
        'Type' = 'EntryNode',
        'W' = 376.95296623355,
        'X' = 900,
        'Y' = 600,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_商店_详情界面
    'smallcard_store_商店_详情界面' = {
        'H' = 83.724494170096,
        'W' = 355.24661589316,
        'X' = 1200,
        'Y' = 0,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.smallcard_store_商店_详情界面_1
    'smallcard_store_商店_详情界面_1' = {
        'H' = 85.648148148148,
        'W' = 376.95296623355,
        'X' = 0,
        'Y' = 1200,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.template
    'template' = {
        'H' = 258.925750489,
        'W' = 208,
        'X' = 481.2,
        'Y' = -724.8,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.设置按钮
    '设置按钮' = {
        'H' = 85.19804526749,
        'Type' = 'EntryNode',
        'W' = 221.9076066593,
        'X' = 300,
        'Y' = 600,
    },
    -- <EntryNode>: $$.template@gui_ctrl.GuiCtrl.设置按钮_hide
    '设置按钮_hide' = {
        'H' = 83.724494170096,
        'Type' = 'EntryNode',
        'W' = 221.9076066593,
        'X' = 1200,
        'Y' = 300,
    },
}
-- ************************************************************************