-- ========================================================================
-- 【UI数据[$$p_3b4f.loot_pool.游戏商店]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_3b4f.loot_pool.游戏商店
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_3b4f.loot_pool.游戏商店
    #CONFIG = {
        'Scale' = 0.66979595336077,
        'Type' = 'EntryModule',
        'X' = -466.81785718519,
        'Y' = 198.13614513297,
    },
    -- <EntryNode>: $$p_3b4f.loot_pool.游戏商店.LootItem
    'LootItem' = {
        'H' = 400.121856,
        'Type' = 'EntryNode',
        'W' = 358.94656,
        'X' = 1232.0,
        'Y' = -74.0,
    },
    -- <EntryNode>: $$p_3b4f.loot_pool.游戏商店.LootItem_1
    'LootItem_1' = {
        'H' = 398.628864,
        'Type' = 'EntryNode',
        'W' = 359.2,
        'X' = 1771.0,
        'Y' = 400.0,
    },
    -- <EntryNode>: $$p_3b4f.loot_pool.游戏商店.LootItem_2
    'LootItem_2' = {
        'H' = 398.628864,
        'Type' = 'EntryNode',
        'W' = 368.0704,
        'X' = 1256.7861111111,
        'Y' = 533.10555555556,
    },
    -- <EntryNode>: $$p_3b4f.loot_pool.游戏商店.LootItem_3
    'LootItem_3' = {
        'H' = 398.628864,
        'Type' = 'EntryNode',
        'W' = 358.94656,
        'X' = 1734.0009259259,
        'Y' = -148.09613119467,
    },
    -- <EntryNode>: $$p_3b4f.loot_pool.游戏商店.LootItem_4
    'LootItem_4' = {
        'H' = 398.628864,
        'Type' = 'EntryNode',
        'W' = 359.444224,
        'X' = 1235.5049259259,
        'Y' = -525.72902335519,
    },
    -- <EntryNode>: $$p_3b4f.loot_pool.游戏商店.LootItem_5
    'LootItem_5' = {
        'H' = 398.628864,
        'Type' = 'EntryNode',
        'W' = 358.94656,
        'X' = 1284.7622237037,
        'Y' = 1061.3402353115,
    },
    -- <EntryNode>: $$p_3b4f.loot_pool.游戏商店.Loot_page
    'Loot_page' = {
        'H' = 294.119424,
        'Type' = 'EntryNode',
        'W' = 513.2224,
        'X' = 636.0,
        'Y' = 325.0,
    },
    -- <EntryNode>: $$p_3b4f.loot_pool.游戏商店.root
    'root' = {
        'H' = 119.43936,
        'Type' = 'EntryNode',
        'W' = 245.976832,
        'X' = 279.0,
        'Y' = 212.0,
    },
}
-- ************************************************************************