-- ========================================================================
-- 【UI数据[$$p_3b4f.unit.防御塔1_2]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_3b4f.unit.防御塔1_2
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_3b4f.unit.防御塔1_2
    #CONFIG = {
        'Scale' = 1.0,
        'Type' = 'EntryModule',
        'X' = -631.0,
        'Y' = 111.05667220056,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_2.ActorEffect
    'ActorEffect' = {
        'AttachedTo' = 'Search',
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 312.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_2.ActorEffect_1
    'ActorEffect_1' = {
        'AttachedTo' = 'Damage',
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 312.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_2.Damage
    'Damage' = {
        'H' = 382.0,
        'Type' = 'EntryNode',
        'W' = 327.0,
        'X' = 3113.0,
        'Y' = 552.44332779944,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_2.Model
    'Model' = {
        'H' = 143.0,
        'Type' = 'EntryNode',
        'W' = 386.0,
        'X' = 666.0,
        'Y' = 473.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_2.Particle
    'Particle' = {
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 386.0,
        'X' = 2982.0,
        'Y' = 1094.4433277994,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_2.Particle_1
    'Particle_1' = {
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 386.0,
        'X' = 3458.0,
        'Y' = 857.44332779944,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_2.PersistLoop
    'PersistLoop' = {
        'H' = 317.0,
        'Type' = 'EntryNode',
        'W' = 377.0,
        'X' = 1107.0,
        'Y' = -18.556672200561,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_2.PolarOffset
    'PolarOffset' = {
        'H' = 477.0,
        'Type' = 'EntryNode',
        'W' = 569.0,
        'X' = 1701.0,
        'Y' = 308.44332779944,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_2.Search
    'Search' = {
        'H' = 677.0,
        'Type' = 'EntryNode',
        'W' = 550.0,
        'X' = 2355.0,
        'Y' = 300.44332779944,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_2.Spell
    'Spell' = {
        'H' = 444.0,
        'Type' = 'EntryNode',
        'W' = 384.0,
        'X' = 641.0,
        'Y' = -83.556672200561,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_2.root
    'root' = {
        'H' = 353.0,
        'Type' = 'EntryNode',
        'W' = 262.0,
        'X' = 296.0,
        'Y' = 301.0,
    },
}
-- ************************************************************************