-- ========================================================================
-- 【UI数据[$$p_3b4f.item.掉落金币]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_3b4f.item.掉落金币
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_3b4f.item.掉落金币
    #CONFIG = {
        'Scale' = 1.0,
        'Type' = 'EntryModule',
        'X' = -230.5,
        'Y' = 374.0,
    },
    -- <EntryNode>: $$p_3b4f.item.掉落金币.PlayerModifyAttribute
    'PlayerModifyAttribute' = {
        'H' = 357.0,
        'Type' = 'EntryNode',
        'W' = 259.0,
        'X' = 647.0,
        'Y' = 457.0,
    },
    -- <EntryNode>: $$p_3b4f.item.掉落金币.default_units_ts_Model
    'default_units_ts_Model' = {
        'H' = 143.0,
        'Type' = 'EntryNode',
        'W' = 386.0,
        'X' = 1242.0,
        'Y' = 0,
    },
    -- <EntryNode>: $$p_3b4f.item.掉落金币.default_units_ts_Unit
    'default_units_ts_Unit' = {
        'H' = 318.0,
        'Type' = 'EntryNode',
        'W' = 315.0,
        'X' = 731.0,
        'Y' = 0,
    },
    -- <EntryNode>: $$p_3b4f.item.掉落金币.root
    'root' = {
        'H' = 224.0,
        'Type' = 'EntryNode',
        'W' = 535.0,
        'X' = 0,
        'Y' = 0,
    },
}
-- ************************************************************************