-- ========================================================================
-- 【UI数据[$$p_3b4f.actor.冰冻塔表现]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_3b4f.actor.冰冻塔表现
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_3b4f.actor.冰冻塔表现
    #CONFIG = {
        'Scale' = 1.0,
        'Type' = 'EntryModule',
        'X' = -24.611111111111,
        'Y' = 342.75,
    },
    -- <EntryNode>: $$p_3b4f.actor.冰冻塔表现.Particle
    'Particle' = {
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 386.0,
        'X' = 608.0,
        'Y' = 24.0,
    },
    -- <EntryNode>: $$p_3b4f.actor.冰冻塔表现.root
    'root' = {
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 227.0,
        'X' = 300,
        'Y' = 0,
    },
}
-- ************************************************************************