-- ========================================================================
-- 【实例模块[unit.防御塔1_3]配置文件】
-- 说明：
--   1、#NIL代表强制赋值为nil，无视继承值。
--   2、#CONFIG代表当前配置文件对应实例模块自身的配置。
-- ========================================================================

-- ************************************************************************
[#CONFIG]
'Version' = 14
'DisplayName' = '[EntryModule][$$p_3b4f.unit.防御塔1_3].DisplayName'
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.ActorBeam]
['ActorBeam']
'Version' = 1
'NodeType' = '$$.actor.ActorBeam'
'Inherit' = '$$.template@actor.ActorBeam.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Effect' = 'Particle_1',
        'LaunchSocketName' = 'socket_weapon',
        'Duration' = 10,
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.ActorEffect]
['ActorEffect']
'Version' = 1
'NodeType' = '$$.actor.ActorEffect'
'Inherit' = '$$.template@actor.ActorEffect.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Offset' = {
            'Z' = 300,
        },
        'Effect' = 'Particle',
        'Scale' = 0.5,
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.ActorEffect_1]
['ActorEffect_1']
'Version' = 1
'NodeType' = '$$.actor.ActorEffect'
'Inherit' = '$$.template@actor.ActorEffect.root'
'Data' = {
    'Editor' = {
        'EditorSuffix' = '1',
    },
    'Game' = {
        'Effect' = 'Particle_2',
        'Scale' = 3,
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.ActorEffect_2]
['ActorEffect_2']
'Version' = 1
'NodeType' = '$$.actor.ActorEffect'
'Inherit' = '$$.template@actor.ActorEffectOneShot.root'
'Data' = {
    'Editor' = {
        'EditorSuffix' = '2',
    },
    'Game' = {
        'Effect' = 'Particle_3',
        'Scale' = 2.5,
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.AddBuff]
['AddBuff']
'Version' = 1
'NodeType' = '$$.effect.EffectAddBuff'
'Inherit' = '$$.template@effect.EffectAddBuff.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'ActorArray' = {
            1 = 'ActorBeam',
            2 = 'ActorEffect_1',
        },
        'BuffLink' = 'Buff',
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.Buff]
['Buff']
'Version' = 1
'NodeType' = '$$.buff.Buff'
'Inherit' = '$$.template@buff.Buff.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Duration' = {
            'Value' = 10,
            'LuaCode' = '(function ()\r\n        local func = function (EffectParam)\r\n            return 10\r\n        end\r\n        return func\r\n    end)()',
        },
        'InitialEffect' = 'UnitModifyAttribute',
        'ExpireEffect' = #NIL,
        'FinalEffect' = 'UnitKill',
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.Model]
['Model']
'Version' = 1
'NodeType' = '$$.model.Model'
'Inherit' = '$$.template@model.Model.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Asset' = 'deco/dungeon/sk_garden_stonetower_a04/model.prefab',
        'AnimMapping' = {
            #IS_OVERWRITE = true,
        },
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.Particle]
['Particle']
'Version' = 1
'NodeType' = '$$.particle.Particle'
'Inherit' = '$$.template@particle.Particle.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Asset' = 'effect/effect_new/effect_scene/eff_chuansongmen_11/particle.effect',
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.Particle_1]
['Particle_1']
'Version' = 1
'NodeType' = '$$.particle.Particle'
'Inherit' = '$$.template@particle.Particle.root'
'Data' = {
    'Editor' = {
        'EditorSuffix' = '1',
    },
    'Game' = {
        'Asset' = 'effect/effect_new/effect_boss/eff_yingmo_skill02/particle.effect',
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.Particle_2]
['Particle_2']
'Version' = 1
'NodeType' = '$$.particle.Particle'
'Inherit' = '$$.template@particle.Particle.root'
'Data' = {
    'Editor' = {
        'EditorSuffix' = '2',
    },
    'Game' = {
        'Asset' = 'effect/effect_new/effect_debuff/eff_debuff_07/particle.effect',
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.Particle_3]
['Particle_3']
'Version' = 1
'NodeType' = '$$.particle.Particle'
'Inherit' = '$$.template@particle.Particle.root'
'Data' = {
    'Editor' = {
        'EditorSuffix' = '3',
    },
    'Game' = {
        'Asset' = 'effect/effect_new/effect_hit/eff_hit_13/particle.effect',
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.Set]
['Set']
'Version' = 1
'NodeType' = '$$.effect.EffectSet'
'Inherit' = '$$.template@effect.EffectSet.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'EffectArray' = {
            1 = 'UnitModifyHeight',
            2 = 'AddBuff',
        },
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.Spell]
['Spell']
'Version' = 1
'NodeType' = '$$.spell.Spell'
'Inherit' = '$$.template@spell.SpellRootUnit.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Effect' = 'Set',
        'SpellEventEffects' = {
            'on_cast_start' = #FORCE_NIL,
            'on_upgrade' = 'SpellModifyCool',
        },
        'Range' = 1000,
        'Cost' = {
            'Cooldown' = 16,
        },
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.SpellModifyCool]
['SpellModifyCool']
'Version' = 1
'NodeType' = '$$.effect.EffectSpellModifyCool'
'Inherit' = '$$.template@effect.EffectSpellModifyCool.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Value' = {
            'IsFunc' = false,
            'Value' = -1,
            'LuaCode' = '(function ()\r\n        local func = function (EffectParam)\r\n            return -1\r\n        end\r\n        return func\r\n    end)()',
        },
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.UnitKill]
['UnitKill']
'Version' = 1
'NodeType' = '$$.effect.EffectUnitKill'
'Inherit' = '$$.template@effect.EffectUnitKill.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'ActorArray' = {
            1 = 'ActorEffect_2',
        },
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.UnitModifyAttribute]
['UnitModifyAttribute']
'Version' = 1
'NodeType' = '$$.effect.EffectUnitModifyAttribute'
'Inherit' = '$$.template@effect.EffectUnitModifyAttribute.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'KeyValuePairs' = {
            1 = {
                'Key' = '移动速度',
                'Value' = {
                    'IsFunc' = false,
                    'Value' = 0,
                    'LuaCode' = '(function ()\r\n        local func = function (EffectParam)\r\n            return 0\r\n        end\r\n        return func\r\n    end)()',
                },
                'Random' = 0,
                'Percentage' = false,
            },
            'IsOverwrite' = true,
            #IS_OVERWRITE = true,
        },
        'Operation' = 'Set',
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.UnitModifyHeight]
['UnitModifyHeight']
'Version' = 1
'NodeType' = '$$.effect.EffectUnitModifyHeight'
'Inherit' = '$$.template@effect.EffectUnitModifyHeight.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'HeightDelta' = 300,
        'Duration' = 3,
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$p_3b4f.unit.防御塔1_3.root]
['root']
'Version' = 1
'NodeType' = '$$.unit.Unit'
'Inherit' = '$$spark_core.template@unit.UnitStructure.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Name' = '[EntryNode][$$p_3b4f.unit.防御塔1_3.root].Data.Game.Name',
        'Attribute' = {
            '攻击' = #PLACEHOLDER,
            '攻击速度' = #PLACEHOLDER,
            '生命' = #PLACEHOLDER,
            '生命上限' = #PLACEHOLDER,
            '搜敌范围' = 1000,
        },
        'ActorArray' = {
            1 = 'ActorEffect',
        },
        'UnitData' = {
            'HeroSkill' = {
                1 = 'Spell',
            },
            'Block' = {
                'Footpoint' = [[■■■■■
■■■■■
■■■■■
■■■■■
■■■■■]],
            },
        },
        'ModelData' = 'Model',
    },
}
'UIConfig' = {
}
-- ************************************************************************