-- ========================================================================
-- 【UI数据[$$p_3b4f.unit.防御塔1_3]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_3b4f.unit.防御塔1_3
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_3b4f.unit.防御塔1_3
    #CONFIG = {
        'Scale' = 1,
        'Type' = 'EntryModule',
        'X' = -167.0,
        'Y' = 18.189160156623,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.ActorBeam
    'ActorBeam' = {
        'AttachedTo' = 'AddBuff',
        'H' = 189.0,
        'Type' = 'EntryNode',
        'W' = 276.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.ActorEffect
    'ActorEffect' = {
        'AttachedTo' = 'root',
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 242.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.ActorEffect_1
    'ActorEffect_1' = {
        'AttachedTo' = 'AddBuff',
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 242.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.ActorEffect_2
    'ActorEffect_2' = {
        'AttachedTo' = 'UnitKill',
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 312.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.AddBuff
    'AddBuff' = {
        'H' = 490.0,
        'Type' = 'EntryNode',
        'W' = 314.0,
        'X' = 1682.0,
        'Y' = 489.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.Buff
    'Buff' = {
        'H' = 283.0,
        'Type' = 'EntryNode',
        'W' = 370.0,
        'X' = 2060.0,
        'Y' = 555.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.Model
    'Model' = {
        'H' = 143.0,
        'Type' = 'EntryNode',
        'W' = 386.0,
        'X' = 666.0,
        'Y' = 473.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.Particle
    'Particle' = {
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 386.0,
        'X' = 624.0,
        'Y' = 678.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.Particle_1
    'Particle_1' = {
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 386.0,
        'X' = 2070.0,
        'Y' = 967.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.Particle_2
    'Particle_2' = {
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 386.0,
        'X' = 2058.0,
        'Y' = 1120.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.Particle_3
    'Particle_3' = {
        'H' = 119.0,
        'Type' = 'EntryNode',
        'W' = 386.0,
        'X' = 2943.0,
        'Y' = 1119.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.Set
    'Set' = {
        'H' = 252.0,
        'Type' = 'EntryNode',
        'W' = 299.0,
        'X' = 1268.0,
        'Y' = 271.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.Spell
    'Spell' = {
        'H' = 444.0,
        'Type' = 'EntryNode',
        'W' = 424.0,
        'X' = 672.0,
        'Y' = -12.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.SpellModifyCool
    'SpellModifyCool' = {
        'H' = 237.0,
        'Type' = 'EntryNode',
        'W' = 259.0,
        'X' = 1200.0,
        'Y' = 631.81083984338,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.UnitKill
    'UnitKill' = {
        'H' = 292.0,
        'Type' = 'EntryNode',
        'W' = 327.0,
        'X' = 2528.0,
        'Y' = 898.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.UnitModifyAttribute
    'UnitModifyAttribute' = {
        'H' = 407.0,
        'Type' = 'EntryNode',
        'W' = 343.0,
        'X' = 2530.0,
        'Y' = 189.81083984338,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.UnitModifyHeight
    'UnitModifyHeight' = {
        'H' = 217.0,
        'Type' = 'EntryNode',
        'W' = 287.0,
        'X' = 1702.0,
        'Y' = 216.0,
    },
    -- <EntryNode>: $$p_3b4f.unit.防御塔1_3.root
    'root' = {
        'H' = 468.0,
        'Type' = 'EntryNode',
        'W' = 262.0,
        'X' = 296.0,
        'Y' = 301.0,
    },
}
-- ************************************************************************