{
    "ElementName":"FunctionDefine",
    "actions":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"SetValue",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"",
                "flags":{
                },
                "left":{
                    "ElementName":"Index",
                    "baseValue":{
                        "ElementName":"SourceValue",
                        "breakPointInfo":{
                            "disabled":false,
                            "hasBreakPoint":false,
                            "type":2
                        },
                        "displayName":"",
                        "flags":{
                        },
                        "staticWarningMsgs":{
                            "__TYPE":"Array",
                            "contents":{
                            }
                        },
                        "tips":"",
                        "valueSource":{
                            "ElementName":"Source",
                            "targetUninit":{
                                "id":"Variable:新变量:3469838712",
                                "packageName":"__validator__",
                                "s_or_c":"client"
                            }
                        }
                    },
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                        "fromOop":true
                    },
                    "indexSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ__gui_ctrl_panel, ClassProperty:show",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":""
                },
                "right":{
                    "ElementName":"Instant",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "type":{
                        "ElementName":"SimpleType",
                        "breakPointInfo":{
                            "disabled":false,
                            "hasBreakPoint":false,
                            "type":2
                        },
                        "displayName":"布尔值",
                        "flags":{
                        },
                        "name":"boolean",
                        "staticWarningMsgs":{
                            "__TYPE":"Array",
                            "contents":{
                            }
                        },
                        "tips":""
                    },
                    "value":true
                },
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            },
            {
                "ElementName":"SetValue",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"",
                "flags":{
                },
                "left":{
                    "ElementName":"Index",
                    "baseValue":{
                        "ElementName":"SourceValue",
                        "breakPointInfo":{
                            "disabled":false,
                            "hasBreakPoint":false,
                            "type":2
                        },
                        "displayName":"",
                        "flags":{
                        },
                        "staticWarningMsgs":{
                            "__TYPE":"Array",
                            "contents":{
                            }
                        },
                        "tips":"",
                        "valueSource":{
                            "ElementName":"Source",
                            "targetUninit":{
                                "id":"Variable:显示面板:4181898556",
                                "packageName":"__validator__",
                                "s_or_c":"client"
                            }
                        }
                    },
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                        "fromOop":true
                    },
                    "indexSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ__gui_ctrl_button, ClassProperty:show",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":""
                },
                "right":{
                    "ElementName":"Instant",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "type":{
                        "ElementName":"SimpleType",
                        "breakPointInfo":{
                            "disabled":false,
                            "hasBreakPoint":false,
                            "type":2
                        },
                        "displayName":"布尔值",
                        "flags":{
                        },
                        "name":"boolean",
                        "staticWarningMsgs":{
                            "__TYPE":"Array",
                            "contents":{
                            }
                        },
                        "tips":""
                    },
                    "value":true
                },
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            },
            {
                "ElementName":"SetValue",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"",
                "flags":{
                },
                "left":{
                    "ElementName":"Index",
                    "baseValue":{
                        "ElementName":"SourceValue",
                        "breakPointInfo":{
                            "disabled":false,
                            "hasBreakPoint":false,
                            "type":2
                        },
                        "displayName":"",
                        "flags":{
                        },
                        "staticWarningMsgs":{
                            "__TYPE":"Array",
                            "contents":{
                            }
                        },
                        "tips":"",
                        "valueSource":{
                            "ElementName":"Source",
                            "targetUninit":{
                                "id":"Variable:显示面板:1352103837",
                                "packageName":"__validator__",
                                "s_or_c":"client"
                            }
                        }
                    },
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                        "fromOop":true
                    },
                    "indexSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ__gui_ctrl_panel, ClassProperty:show",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":""
                },
                "right":{
                    "ElementName":"Instant",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "type":{
                        "ElementName":"SimpleType",
                        "breakPointInfo":{
                            "disabled":false,
                            "hasBreakPoint":false,
                            "type":2
                        },
                        "displayName":"布尔值",
                        "flags":{
                        },
                        "name":"boolean",
                        "staticWarningMsgs":{
                            "__TYPE":"Array",
                            "contents":{
                            }
                        },
                        "tips":""
                    },
                    "value":false
                },
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            },
            {
                "ElementName":"FunctionCall",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"",
                "flags":{
                },
                "funcSource":{
                    "ElementName":"Source",
                    "targetUninit":{
                        "id":"FunctionDefine:send_custom_event1790050304",
                        "packageName":"__client__",
                        "s_or_c":"client"
                    }
                },
                "parameters":{
                    "__TYPE":"Array",
                    "contents":[
                        {
                            "ElementName":"NewClassFunctionCall",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "funcSource":{
                                "ElementName":"Source",
                                "targetUninit":{
                                    "id":"CustomEvent:客户端单击开始游戏:2570494278:Constructor",
                                    "packageName":"p_3b4f",
                                    "s_or_c":"client"
                                }
                            },
                            "parameters":{
                                "__TYPE":"Array",
                                "contents":[
                                    {
                                        "ElementName":"SourceValue",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "staticWarningMsgs":{
                                            "__TYPE":"Array",
                                            "contents":{
                                            }
                                        },
                                        "tips":"",
                                        "valueSource":{
                                            "ElementName":"Source",
                                            "targetUninit":{
                                                "id":"PresetPropertyId:(Preset:游戏247595008, Linkspace:default, PresetKey:游戏)",
                                                "packageName":"__client__",
                                                "s_or_c":"client"
                                            }
                                        }
                                    }
                                ]
                            },
                            "staticWarningMsgs":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            },
                            "tips":"",
                            "typeParameters":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            }
                        }
                    ]
                },
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":"",
                "typeParameters":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                }
            }
        ]
    },
    "breakPointInfo":{
        "disabled":false,
        "hasBreakPoint":false,
        "type":2
    },
    "defaultResetParameterCount":0,
    "description":"",
    "displayName":"func",
    "flags":{
        "hideConfig":true,
        "noSelf":true,
        "pop":true,
        "unchangeName":true,
        "unchangeParameter":true
    },
    "id":"FunctionDefine:func:4267705317",
    "keyword":"",
    "label":"默认",
    "linkspace":"",
    "name":"func",
    "packageName":"__validator__",
    "parameters":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"ctrl",
                "flags":{
                },
                "id":"Variable:ctrl:2969079573",
                "keyword":"",
                "label":"默认",
                "name":"ctrl",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ_gameui_gui_ctrl_normal_btn",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            },
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"mouse_btn_id",
                "flags":{
                },
                "id":"Variable:mouse_btn_id:166823724",
                "keyword":"",
                "label":"默认",
                "name":"mouse_btn_id",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"SimpleType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"数值",
                    "flags":{
                    },
                    "name":"number",
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":""
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            }
        ]
    },
    "rankOrder":0,
    "realReturnType":{
        "ElementName":"SimpleType",
        "breakPointInfo":{
            "disabled":false,
            "hasBreakPoint":false,
            "type":2
        },
        "displayName":"void",
        "flags":{
        },
        "name":"void",
        "staticWarningMsgs":{
            "__TYPE":"Array",
            "contents":{
            }
        },
        "tips":""
    },
    "s_or_c":"client",
    "staticWarningMsgs":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "subsections":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "tips":"",
    "typeParameters":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "typeParametersExtends":{
        "__TYPE":"Map",
        "contents":{
        }
    },
    "uiText":"",
    "v2_version":0.900000,
    "variables":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Variable",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "defaultValue":{
                    "ElementName":"FunctionCall",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "funcSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"FunctionDefine:gui_get_part4248698880.0",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "parameters":{
                        "__TYPE":"Array",
                        "contents":[
                            {
                                "ElementName":"FunctionCall",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                    "enableDisplayName":true
                                },
                                "funcSource":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"FunctionDefine:gui_get_main_page1445330944",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                },
                                "parameters":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "typeParameters":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                }
                            },
                            {
                                "ElementName":"Instant",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                    "enableDisplayName":true
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "type":{
                                    "ElementName":"SimpleType",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"字符串",
                                    "flags":{
                                    },
                                    "name":"string",
                                    "staticWarningMsgs":{
                                        "__TYPE":"Array",
                                        "contents":{
                                        }
                                    },
                                    "tips":""
                                },
                                "value":"显示面板"
                            }
                        ]
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeParameters":{
                        "__TYPE":"Array",
                        "contents":[
                            {
                                "ElementName":"InstanceType",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                },
                                "source":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"Class:_OBJ__gui_ctrl_panel",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "typeArgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                }
                            }
                        ]
                    }
                },
                "displayName":"显示面板",
                "flags":{
                },
                "id":"Variable:新变量:3469838712",
                "keyword":"",
                "label":"默认",
                "name":"显示面板",
                "packageName":"__validator__",
                "rankOrder":0,
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ__gui_ctrl_panel",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            },
            {
                "ElementName":"Variable",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "defaultValue":{
                    "ElementName":"FunctionCall",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "funcSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"FunctionDefine:gui_get_part4248698880.0",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "parameters":{
                        "__TYPE":"Array",
                        "contents":[
                            {
                                "ElementName":"FunctionCall",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                    "enableDisplayName":true
                                },
                                "funcSource":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"FunctionDefine:gui_get_main_page1445330944",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                },
                                "parameters":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "typeParameters":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                }
                            },
                            {
                                "ElementName":"Instant",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                    "enableDisplayName":true
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "type":{
                                    "ElementName":"SimpleType",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"字符串",
                                    "flags":{
                                    },
                                    "name":"string",
                                    "staticWarningMsgs":{
                                        "__TYPE":"Array",
                                        "contents":{
                                        }
                                    },
                                    "tips":""
                                },
                                "value":"商店按钮"
                            }
                        ]
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeParameters":{
                        "__TYPE":"Array",
                        "contents":[
                            {
                                "ElementName":"InstanceType",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                },
                                "source":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"Class:_OBJ__gui_ctrl_button",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "typeArgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                }
                            }
                        ]
                    }
                },
                "displayName":"商店按钮",
                "flags":{
                },
                "id":"Variable:显示面板:4181898556",
                "keyword":"",
                "label":"默认",
                "name":"商店按钮",
                "packageName":"__validator__",
                "rankOrder":0,
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ__gui_ctrl_button",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            },
            {
                "ElementName":"Variable",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "defaultValue":{
                    "ElementName":"FunctionCall",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "funcSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"FunctionDefine:gui_get_part4248698880.0",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "parameters":{
                        "__TYPE":"Array",
                        "contents":[
                            {
                                "ElementName":"FunctionCall",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                    "enableDisplayName":true
                                },
                                "funcSource":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"FunctionDefine:gui_get_main_page1445330944",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                },
                                "parameters":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "typeParameters":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                }
                            },
                            {
                                "ElementName":"Instant",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                    "enableDisplayName":true
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "type":{
                                    "ElementName":"SimpleType",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"字符串",
                                    "flags":{
                                    },
                                    "name":"string",
                                    "staticWarningMsgs":{
                                        "__TYPE":"Array",
                                        "contents":{
                                        }
                                    },
                                    "tips":""
                                },
                                "value":"开始菜单"
                            }
                        ]
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeParameters":{
                        "__TYPE":"Array",
                        "contents":[
                            {
                                "ElementName":"InstanceType",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                },
                                "source":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"Class:_OBJ__gui_ctrl_panel",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "typeArgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                }
                            }
                        ]
                    }
                },
                "displayName":"开始菜单",
                "flags":{
                },
                "id":"Variable:显示面板:1352103837",
                "keyword":"",
                "label":"默认",
                "name":"开始菜单",
                "packageName":"__validator__",
                "rankOrder":0,
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ__gui_ctrl_panel",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            }
        ]
    }
}