-- ========================================================================
-- 【UI数据[$$p_3b4f.spell.新建防御塔_5]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_3b4f.spell.新建防御塔_5
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_3b4f.spell.新建防御塔_5
    #CONFIG = {
        'Scale' = 0.83333333333333,
        'Type' = 'EntryModule',
        'X' = 171.09444444444,
        'Y' = 114.4,
    },
    -- <EntryNode>: $$p_3b4f.spell.新建防御塔_5.root
    'root' = {
        'H' = 399.6,
        'Type' = 'EntryNode',
        'W' = 390.4,
        'X' = 300,
        'Y' = 0,
    },
    -- <Lnk>: $$p_3b4f.unit.防御塔1_4.root
    'unit.防御塔1_4.root' = {
        'H' = 79.2,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 844.10555555556,
        'Y' = 252.8,
    },
}
-- ************************************************************************