-- ========================================================================
-- 【UI数据[$$lib_control.template@gui_ctrl.lib_control_main]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$lib_control.template@gui_ctrl.lib_control_main
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$lib_control.template@gui_ctrl.lib_control_main
    #CONFIG = {
    },
    -- <EntryNode>: $$lib_control.template@gui_ctrl.lib_control_main.root
    'root' = {
        'H' = 84.0,
        'W' = 246.0,
        'X' = 900,
        'Y' = 0,
    },
    -- <EntryNode>: $$lib_control.template@gui_ctrl.lib_control_main.template
    'template' = {
        'W' = 225.0,
        'X' = 1500,
        'Y' = 0,
    },
    -- <EntryNode>: $$lib_control.template@gui_ctrl.lib_control_main.中止施法区域
    '中止施法区域' = {
        'H' = 84.0,
        'W' = 279.0,
        'X' = 600,
        'Y' = 300,
    },
    -- <EntryNode>: $$lib_control.template@gui_ctrl.lib_control_main.交互摇杆
    '交互摇杆' = {
        'H' = 84.0,
        'W' = 223.0,
        'X' = 600,
        'Y' = 0,
    },
    -- <EntryNode>: $$lib_control.template@gui_ctrl.lib_control_main.技能摇杆组
    '技能摇杆组' = {
        'H' = 84.0,
        'W' = 251.0,
        'X' = 300,
        'Y' = 0,
    },
    -- <EntryNode>: $$lib_control.template@gui_ctrl.lib_control_main.施法进度条
    '施法进度条' = {
        'H' = 84.0,
        'W' = 251.0,
        'X' = 0,
        'Y' = 300,
    },
    -- <EntryNode>: $$lib_control.template@gui_ctrl.lib_control_main.移动摇杆
    '移动摇杆' = {
        'H' = 84.0,
        'W' = 223.0,
        'X' = 1200,
        'Y' = 0,
    },
    -- <EntryNode>: $$lib_control.template@gui_ctrl.lib_control_main.移动键盘
    '移动键盘' = {
        'H' = 84.0,
        'W' = 223.0,
        'X' = 300,
        'Y' = 300,
    },
}
-- ************************************************************************