-- ========================================================================
-- 【UI数据[$$p_3b4f.level.第一关]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_3b4f.level.第一关
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_3b4f.level.第一关
    #CONFIG = {
        'Scale' = 1.44,
        'Type' = 'EntryModule',
        'X' = -310.44056178559,
        'Y' = -676.96149582465,
    },
    -- <EntryNode>: $$p_3b4f.level.第一关.Spawner
    'Spawner' = {
        'H' = 259.2,
        'Type' = 'EntryNode',
        'W' = 239.2,
        'X' = 1061.9475543782,
        'Y' = 25.088106516197,
    },
    -- <EntryNode>: $$p_3b4f.level.第一关.Spawner_1
    'Spawner_1' = {
        'H' = 216.0,
        'Type' = 'EntryNode',
        'W' = 236.33333333333,
        'X' = 1066.3209617856,
        'Y' = 344.80143984953,
    },
    -- <EntryNode>: $$p_3b4f.level.第一关.Spawner_2
    'Spawner_2' = {
        'H' = 259.02777777778,
        'Type' = 'EntryNode',
        'W' = 236.33333333333,
        'X' = 1071.4420654893,
        'Y' = 1148.1890398495,
    },
    -- <EntryNode>: $$p_3b4f.level.第一关.Spawner_3
    'Spawner_3' = {
        'H' = 259.02777777778,
        'Type' = 'EntryNode',
        'W' = 236.33333333333,
        'X' = 1067.0686580819,
        'Y' = 828.4757065162,
    },
    -- <EntryNode>: $$p_3b4f.level.第一关.Wave
    'Wave' = {
        'H' = 188.4,
        'Type' = 'EntryNode',
        'W' = 364.66666666667,
        'X' = 630.0,
        'Y' = 236.0,
    },
    -- <EntryNode>: $$p_3b4f.level.第一关.Wave_1
    'Wave_1' = {
        'H' = 188.88888888889,
        'Type' = 'EntryNode',
        'W' = 361.33333333333,
        'X' = 619.14496178559,
        'Y' = 1073.0014398495,
    },
    -- <EntryNode>: $$p_3b4f.level.第一关.root
    'root' = {
        'H' = 189.6,
        'Type' = 'EntryNode',
        'W' = 328.0,
        'X' = 241.0,
        'Y' = 246.0,
    },
}
-- ************************************************************************